language: minimal

services:
  - docker

os:
  - linux

git:
  depth: 1

notifications:
  email: false

jobs:
  fast_finish: true
  include:
  - name: "paket"
    env: GITNOW=paket
    script:
      - docker run -it --rm joseluisq/paket sh -c "fish -c 'paket add joseluisq/gitnow' && fish -c 'gitnow -v'"
  - name: "fisher"
    env: GITNOW=fisher
    script:
      - docker run -it --rm joseluisq/paket sh -c "apk add curl && fish -c 'curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher' && fish -c 'fisher install joseluisq/gitnow && gitnow -v'"
